CREATE DATABASE Catalog;

CREATE TABLE MusicAlbum(
ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
publish_date DATE,
archived BOOLEAN
);

CREATE TABLE genre(
ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name TEXT
);

ALTER TABLE musicalbum ADD COLUMN
genre_id INT REFERENCES genre(id

CREATE TABLE book (
   id SERIAL PRIMARY KEY,
   publisher VARCHAR(50) NOT NULL,
    cover_state INT NOT NULL,
    
);

CREATE TABLE label (
   id SERIAL PRIMARY KEY,
   title VARCHAR(50) NOT NULL,
   color VARCHAR(50) NOT NULL,
   item_id int 
   
);

ALTER TABLE label ADD CONSTRAINT fk_constraint FOREIGN KEY (item_id) REFERENCES item (id);