CREATE DATABASE Catalog;

CREATE TABLE MusicAlbum(
ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
publish_date DATE,
archived BOOLEAN
);

CREATE TABLE genre(
ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name TEXT
);

ALTER TABLE musicalbum ADD COLUMN
genre_id INT REFERENCES genre(id);