require_relative '../classes/genre'
require_relative '../classes/item'
require_relative '../classes/musicalbum'
require_relative '../classes/movie'
require_relative '../classes/source'
require 'yaml'
